# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hotseat < Formula
  desc "Terminal dashboard and CLI for Claude Code and Codex accounts, their quota, and work a usage limit stopped"
  homepage "https://github.com/Maxteabag/hotseat"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Maxteabag/hotseat/releases/download/v0.2.1/hotseat_0.2.1_darwin_amd64.tar.gz"
      sha256 "6c8f10536dba785212e562a7dd8828d11a78232b948dbf5498ade4c6e61b713b"

      define_method(:install) do
        bin.install "hotseat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Maxteabag/hotseat/releases/download/v0.2.1/hotseat_0.2.1_darwin_arm64.tar.gz"
      sha256 "60e38a88327be1b40aa664969674a2fb0f8467411e19dddf1121c0222662e346"

      define_method(:install) do
        bin.install "hotseat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Maxteabag/hotseat/releases/download/v0.2.1/hotseat_0.2.1_linux_amd64.tar.gz"
      sha256 "936d455881f856727a3d305c3775f6e17d20ed160930869d3cecb1bde7fe0ada"
      define_method(:install) do
        bin.install "hotseat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Maxteabag/hotseat/releases/download/v0.2.1/hotseat_0.2.1_linux_arm64.tar.gz"
      sha256 "1299c45965636a24e562da662f0361718a2543567b59ad873ea63d5ab6a1b5b3"
      define_method(:install) do
        bin.install "hotseat"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/hotseat --version")
  end
end
