# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hotseat < Formula
  desc "Terminal dashboard and CLI for Claude Code and Codex accounts, their quota, and work a usage limit stopped"
  homepage "https://github.com/Maxteabag/hotseat"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Maxteabag/hotseat/releases/download/v0.3.0/hotseat_0.3.0_darwin_amd64.tar.gz"
      sha256 "42864a2ff93407bb0e222aeffcf80d6e6073980d2db724b9a058cb77ee362669"

      define_method(:install) do
        bin.install "hotseat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Maxteabag/hotseat/releases/download/v0.3.0/hotseat_0.3.0_darwin_arm64.tar.gz"
      sha256 "0c73bdcdde4d45312313ea16579d5c18c47ff6e5c61c7da666fffbaa6d9c8a0b"

      define_method(:install) do
        bin.install "hotseat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Maxteabag/hotseat/releases/download/v0.3.0/hotseat_0.3.0_linux_amd64.tar.gz"
      sha256 "5b8f50d6ff2d8289a4ba96ff1004a58e4e986836e36276747aae6b03f91021c4"
      define_method(:install) do
        bin.install "hotseat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Maxteabag/hotseat/releases/download/v0.3.0/hotseat_0.3.0_linux_arm64.tar.gz"
      sha256 "9b2790c79494483613aa54ff170a2c40ca1fcd776527771ab26837690ad925e2"
      define_method(:install) do
        bin.install "hotseat"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/hotseat --version")
  end
end
